version: "2"
services:
  raspi-server:
    container_name: ${NAME}
    image: "${REGISTRY_SLASH}${NAME}${COLON_TAG}"
    ports:
      - ${LISTEN_PORT}:10000
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./docker.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure